### PR TITLE
Migrate to null-safety

### LINKED ISSUE #1: Support null safety
This is a request to add support for [null safety](https://dart.dev/null-safety) to `package:animated`.
We depend on your awesome package, so would be great to have null safety enabled.

The Dart/Flutter team already encourages publishing the migrated packages: See [this blog post](https://medium.com/dartlang/preparing-the-dart-and-flutter-ecosystem-for-null-safety-e550ce72c010).

See the [migration guide](https://dart.dev/null-safety/migration-guide) for details about enabling null safety.

### PR DESCRIPTION
**Pull request by IchordeDionysos**
Migrates this package to null-safety.

Closes #1.

### CODE REVIEW

**Comment by IchordeDionysos** [comment]
@Vardiak I did implement null-safety for this package 🚀 

Can you take a look over it, merge it, and publish to pub.dev if it looks good to you?

**Comment by Vardiak** [comment]
@IchordeDionysos Hello, this package is no longer maintained because `TweenAnimationBuilder` ([link](https://api.flutter.dev/flutter/widgets/TweenAnimationBuilder-class.html)) has been introduced to Flutter, which basically does the same thing. Tell me if it would be easier for you that I merge this or if you want to migrate to `TweenAnimationBuilder`.

**Comment by IchordeDionysos** [comment]
@Vardiak ahh yes makes sense, just went through all dependencies and opened issues/PRs :)

**Comment by apalala-dev** [comment]
I am using this package as well and I find it easier to implement than `TweenAnimationBuilder`, could you merge the PR?
Also, if you decide not to, please explain in the README that it should not be used anymore.

**Comment by Vardiak** [comment]
@IchordeDionysos @Kobatsu The update has been published to pub.dev. Thanks for the contribution!

**Pull request merged**
